# Generated by Django 3.2 on 2021-04-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка выпечки'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='weight',
            field=models.IntegerField(verbose_name='Вес выпечки'),
        ),
    ]
