# Generated by Django 3.2 on 2021-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0002_auto_20210417_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория выпечки')),
            ],
        ),
        migrations.CreateModel(
            name='BakeryCategoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название выпечки')),
                ('text', models.TextField(max_length=255, verbose_name='Состав выпечки')),
                ('weight', models.IntegerField(verbose_name='Вес выпечки')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка выпечки')),
            ],
        ),
        migrations.DeleteModel(
            name='Bakery',
        ),
    ]
