# Generated by Django 3.2 on 2021-04-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0003_auto_20210419_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BakeryCategoryItems',
            new_name='Bakery',
        ),
        migrations.AlterModelOptions(
            name='bakery',
            options={'verbose_name': 'Сама выпечки', 'verbose_name_plural': 'Сами выпечки'},
        ),
        migrations.AlterModelOptions(
            name='bakerycategory',
            options={'verbose_name': 'Категория выпечки', 'verbose_name_plural': 'Категория выпечки'},
        ),
    ]
