# Generated by Django 3.2 on 2021-04-20 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0004_auto_20210419_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bakeryapp.bakerycategory', verbose_name='Выбор категории выпечки'),
        ),
        migrations.AlterField(
            model_name='bakerycategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Категория выпечки'),
        ),
    ]
