# Generated by Django 3.2 on 2021-04-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0005_auto_20210420_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakery',
            options={'verbose_name': 'Конкретная выпечка', 'verbose_name_plural': 'Конкретные выпечки'},
        ),
        migrations.AlterField(
            model_name='bakery',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bakeryapp.bakerycategory', verbose_name='Kатегория выпечки'),
        ),
    ]
