# Generated by Django 3.2 on 2021-04-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0006_auto_20210420_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Крем выпечки')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за крем выпечки')),
            ],
            options={
                'verbose_name': 'Крем выпечки',
                'verbose_name_plural': 'Кремы выпечки',
            },
        ),
        migrations.CreateModel(
            name='BakeryDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Диаметр выпечки /см.')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за диаметр выпечки')),
            ],
            options={
                'verbose_name': 'Диаметр выпечки',
                'verbose_name_plural': 'Диаметры выпечки',
            },
        ),
        migrations.CreateModel(
            name='BakeryFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Начинка выпечки')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за начинку выпечки')),
            ],
            options={
                'verbose_name': 'Начинка выпечки',
                'verbose_name_plural': 'Начинки выпечки',
            },
        ),
        migrations.AddField(
            model_name='bakery',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена выпечки'),
        ),
        migrations.CreateModel(
            name='BakeryСonsist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cream', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bakeryapp.bakerycream', verbose_name='Крем выпечки')),
                ('diameter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bakeryapp.bakerydiameter', verbose_name='Диаметр выпечки')),
                ('filling', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bakeryapp.bakeryfilling', verbose_name='Начинка выпечки')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bakeryapp.bakery', verbose_name='Выберите выпечку')),
            ],
            options={
                'verbose_name': 'Состав ',
                'verbose_name_plural': 'Выпечка и ее состав',
            },
        ),
    ]
