# Generated by Django 3.2 on 2021-04-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0007_auto_20210421_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Основа выпечки')),
            ],
            options={
                'verbose_name': 'Основа выпечки',
                'verbose_name_plural': 'Основа выпечки',
            },
        ),
        migrations.RemoveField(
            model_name='bakeryсonsist',
            name='diameter',
        ),
        migrations.DeleteModel(
            name='BakeryDiameter',
        ),
        migrations.AddField(
            model_name='bakeryсonsist',
            name='basis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bakeryapp.bakerybasis', verbose_name='Основа выпечки'),
        ),
    ]
