# Generated by Django 3.2 on 2021-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0008_auto_20210421_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryсonsist',
            options={'verbose_name': 'Состав ', 'verbose_name_plural': 'Заказы выпечек'},
        ),
        migrations.AddField(
            model_name='bakeryсonsist',
            name='customer',
            field=models.CharField(default='Имя покупателя', max_length=255, verbose_name='Имя заказчика'),
        ),
        migrations.AddField(
            model_name='bakeryсonsist',
            name='phone',
            field=models.CharField(default='Телефон покупателя', max_length=255, verbose_name='Телефон заказчика'),
        ),
        migrations.AddField(
            model_name='bakeryсonsist',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Общая цена выпечки'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='price',
            field=models.IntegerField(verbose_name='Цена выпечки'),
        ),
    ]
