# Generated by Django 3.2 on 2021-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0009_auto_20210422_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryсonsist',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='bakeryсonsist',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон заказчика'),
        ),
        migrations.AlterField(
            model_name='bakeryсonsist',
            name='price',
            field=models.IntegerField(verbose_name='Общая цена выпечки'),
        ),
    ]
