# Generated by Django 3.2 on 2021-04-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0010_auto_20210429_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryсonsist',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Детали заказа выпечек'},
        ),
    ]
